InternNest/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('HomePage.urls', namespace='home')),
    url(r'^terms/', include('HomePage.urls', namespace='home')),
    url(r'^profile/', include('Profile.urls', namespace='Profile')),
    url(r'^register/', include('UserRegistration.urls', namespace='UserRegistration')),
    url(r'^create/job/', include('CreateJob.urls', namespace='CreateJob')),
    url(r'^admin/', include(admin.site.urls)),
)

Profile/urls.py
from django.conf.urls import patterns, url
from Profile import views

urlpatterns = patterns('',
    url(r'^$', views.profileView, name='profileView'),
    url(r'^contactinfo/$', views.contactInfo, name='contactInfo'),
)

CreateJob/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Job(models.Model):
    creator = models.ForeignKey(get_user_model())
    
    title = models.CharField(max_length=100)
    duration = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    is_paid = models.BooleanField(default=True)
    description = models.CharField(max_length=800)
    is_public = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title

Profile/models.py
from django.db import models

# Create your models here.

Profile/forms.py
from django.forms import CharField, EmailField, Form, TextInput


class ContactInfoForm(Form):
    phone = CharField(max_length=100, required=False, widget=TextInput(attrs={'class':'textboxWithPlaceholder'}))
    email = EmailField(max_length=254, widget=TextInput(attrs={'class':'textboxWithPlaceholder'}))
    address = CharField(max_length=100, required=False, widget=TextInput(attrs={'class':'textboxWithPlaceholder'}))
    

Profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from Profile.forms import ContactInfoForm


# Create your views here.
def profileView(request):
    if request.user.is_authenticated():
        if request.user.is_student():
            return render(request, 'Profile/student_profile.html', {})
        if request.user.is_business():
            return render(request, 'Profile/business_profile.html', {})
        if request.user.is_school():
            return render(request, 'Profile/school_profile.html', {})
            
        # Fallback to a default profile for now
        return HttpResponse("Unsupported user type")
    else:
        return HttpResponseRedirect('/register/')


def contactInfo(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/register/login/')
    
    if request.method == 'POST':
        form = ContactInfoForm(request.POST)
        if form.is_valid():
            # Update the user object and save
            request.user.phone = form.cleaned_data['phone'];
            request.user.email = form.cleaned_data['email'];
            request.user.address = form.cleaned_data['address'];
            request.user.save(update_fields=['phone', 'email', 'address'])
            
            # Return to the user's profile
            return HttpResponseRedirect('/profile/')
    else:
        initial = {
            'email': request.user.email, 
            'phone': request.user.phone, 
            'address': request.user.address
        }
        form = ContactInfoForm(
            initial=initial
        )
        
    return render(request, 'Profile/contact_info.html', {'form': form})

Profile/templates/Profile/business_profile.html
{% extends "base.html" %}

{% block content %}
<div id="contentDiv" style="width:800px; margin-left:auto; margin-right:auto; margin-top:30px;">
  <div style="font-size:35px; padding-right:20px;">
    {{ user.get_full_name }}
  </div>
  
  <div style="float:left; width:190px;">
    <div style="background-color:white; width:160px; height:160px; border:1px solid black; line-height:160px; text-align:center;">
      <span style="color:gray;">
        profile image
      </span>
    </div>
    <span class="TextSubtleStyle">
      business profile
    </span>
  </div>
  
  <div style="float:left; width:610px;">
    <table style="width:100%;">
      <tr>
        <td>
          <span class="TextTitle2Style">
            Jobs
          </span>
        </td>
        <td style="text-align:right; vertical-align: bottom;">
          <span class="TextNormalStyle">
            <a href="/create/job/"> create </a>
          </span>
        </td>
      </tr>
    </table>
    
    <div class="Divider"></div>
    <div class="SpacerMedium"></div>
    
    {% if user.job_set.all %}
      {% for job in user.job_set.all %}
        {{ job.title }}
        <div class="SpacerSmall"></div>
      {% endfor %}
    {% else %}
      <div class="TextSubtleStyle">
        You haven't created any jobs yet.
      </div>
    {% endif %}

    
    <div class="SpacerLarge"></div>
    
    <table style="width:100%;">
      <tr >
        <td>
          <span class="TextTitle2Style">
            Contact Info
          </span>
        </td>
        <td style="text-align:right; vertical-align: bottom;">
          <span class="TextNormalStyle">
            <a href="/profile/contactinfo/"> 
              edit
            </a>
          </span>
        </td>
      </tr>
    </table>
    
    <div class="Divider"></div>
    
    <div class="SpacerMedium"></div>
    
    <div class="TextNormalStyle">
      Phone #: {{ user.phone }}
      
      <div class="SpacerSmall"></div>
      
      Email: {{ user.email }}
      
      <div class="SpacerSmall"></div>
      
      Address: {{ user.address }}
    </div>
  </div>
</div>

{% endblock %}

Profile/templates/Profile/contact_info.html
{% extends "base.html" %}

{% block content %}

<div id="contentDiv" style="width:800px; margin-left:auto; margin-right:auto; margin-top:30px;">
  <div style="float:left; width:190px;">
    <div class="TextTitle1Style">
      Contact Info
    </div>
  </div>
  
  <div style="float:left; width:610px;">
    <form action="/profile/contactinfo/" method="post">
      {% csrf_token %}
      
      <div class="TextNormalStyle">
        Phone
      </div>
      <div style="width:320px; position:relative;">
        <div class="textboxPlaceholder"> (123) 456-7890 </div>
        {{ form.phone }}
      </div>
      {% if form.phone.errors %}
        <div class="TextErrorStyle">
          {{ form.phone.errors.as_text }}
        </div>
      {% endif %}
      <div class="SpacerMedium"></div>
      
      <div class="TextNormalStyle">
        Email
      </div>
      <div style="width:320px; position:relative;">
        <div class="textboxPlaceholder"> someone@email.com </div>
        {{ form.email }}
      </div>
      {% if form.email.errors %}
        <div class="TextErrorStyle">
          {{ form.email.errors.as_text }}
        </div>
      {% endif %}
      <div class="SpacerMedium"></div>
      
      <div class="TextNormalStyle">
        Address
      </div>
      <div style="width:320px; position:relative;">
        <div class="textboxPlaceholder"> Toronto, ON, Canada </div>
        {{ form.address }}
      </div>
      {% if form.address.errors %}
        <div class="TextErrorStyle">
          {{ form.address.errors.as_text }}
        </div>
      {% endif %}
      
      <div class="SpacerLarge"></div>
      
      <input type="submit" value="Save"/>
    </form>
  </div>
</div>

{% endblock %}

Profile/templates/Profile/school_profile.html
{% extends "base.html" %}

{% block content %}
<div id="contentDiv" style="width:800px; margin-left:auto; margin-right:auto; margin-top:30px;">
  <div style="font-size:35px; padding-right:20px;">
    {{ user.get_full_name }}
  </div>
  
  <div style="float:left; width:190px;">
    <div style="background-color:white; width:160px; height:160px; border:1px solid black; line-height:160px; text-align:center;">
      <span style="color:gray;">
        profile image
      </span>
    </div>
    <span class="TextSubtleStyle">
      school profile
    </span>
  </div>

  <div style="float:left; width:610px;">
    <table style="width:100%;">
      <tr >
        <td>
          <span class="TextTitle2Style">
            Contact Info
          </span>
        </td>
        <td style="text-align:right; vertical-align: bottom;">
          <span class="TextNormalStyle">
            <a href="/profile/contactinfo/"> 
              edit
            </a>
          </span>
        </td>
      </tr>
    </table>
    
    <div class="Divider"></div>
    
    <div class="SpacerMedium"></div>
    
    <div class="TextNormalStyle">
      Phone #: {{ user.phone_number }}
      
      <div class="SpacerSmall"></div>
      
      Email: {{ user.email }}
      
      <div class="SpacerSmall"></div>
      
      Address: {{ user.address }}
    </div>
  </div>
</div>

{% endblock %}

Profile/templates/Profile/student_profile.html
{% extends "base.html" %}

{% block content %}
<div id="contentDiv" style="width:800px; margin-left:auto; margin-right:auto; margin-top:30px;">
  <div style="font-size:35px; padding-right:20px;">
    {{ user.get_full_name }}
  </div>
  
  <div style="float:left; width:190px;">
    <div style="background-color:white; width:160px; height:160px; border:1px solid black; line-height:160px; text-align:center;">
      <span style="color:gray;">
        student profile
      </span>
    </div>
    
    <div class="SpacerLarge"></div>
    
    <div class="TextTitle2Style">
      <u> Profile </u>
    </div>
    <div class="TextTitle2Style">
      Internships
    </div>
    <div class="TextTitle2Style">
      Status
    </div>
    <div class="TextTitle2Style">
      Connections
    </div>
    <div class="TextTitle2Style">
      Search
    </div>
  </div>

  <div style="float:left; width:610px;">
    <table style="width:100%;">
      <tr>
        <td>
          <span class="TextTitle2Style">
            Education
          </span>
        </td>
        <td style="text-align:right; vertical-align: bottom;">
          <span class="TextNormalStyle">
            <a href="/profile/edit/"> 
              edit
            </a>
          </span>
        </td>
      </tr>
    </table>
    
    <div class="Divider"></div>
    
    <div class="SpacerLarge"></div>
    
    <table style="width:100%;">
      <tr>
        <td>
          <span class="TextTitle2Style">
            Experience
          </span>
        </td>
        <td style="text-align:right; vertical-align: bottom;">
          <span class="TextNormalStyle">
            <a href="/profile/edit/"> 
              edit
            </a>
          </span>
        </td>
      </tr>
    </table>
    
    <div class="Divider"></div>
    
    <div class="SpacerLarge"></div>
  
    <table style="width:100%;">
      <tr>
        <td>
          <span class="TextTitle2Style">
            Contact Info
          </span>
        </td>
        <td style="text-align:right; vertical-align: bottom;">
          <span class="TextNormalStyle">
            <a href="/profile/contactinfo/"> 
              edit
            </a>
          </span>
        </td>
      </tr>
    </table>
    
    <div class="Divider"></div>
    
    <div class="SpacerMedium"></div>
    
    <div class="TextNormalStyle">
      Phone #: {{ user.phone_number }}
      
      <div class="SpacerSmall"></div>
      
      Email: {{ user.email }}
      
      <div class="SpacerSmall"></div>
      
      Address: {{ user.address }}
    </div>
  </div>
</div>

{% endblock %}